### ISSUE TITLE
installation steps

### ISSUE THREAD

**Issue by romanchyla** [pblankley/interp-workshop-2019#1]
i tried with python3.7, but gave up after numpy release was not available (forgot exactly what the error was)

this worked for python2.7 for me

```(venv) interp-workshop-2019 master → gdiff
diff --git a/requirements.txt b/requirements.txt
index 2df705d..e2b921e 100644
--- a/requirements.txt
+++ b/requirements.txt
@@ -1,4 +1,4 @@
-numpy==1.14.5
+numpy
 pandas==0.23.4
 matplotlib==2.2.3
 seaborn==0.9.0
@@ -8,9 +8,10 @@ scikit-image==0.14.1
 scikit-learn==0.20.1
 lime==0.1.1.29
 shap== 0.27.0
-ipython==6.1.0
+ipython
 jupyter==1.0.0
 h5py==2.8.0
 numba==0.39.0
 cvxpy==1.0.14
 aif360==0.2.0
+notebook==5.7.2
```

**Comment by SpyderAlba** [comment]
Python 2.7 did not work for me. I am using 3.6 conda env

```
conda create -n interpenv python=3.6
conda activate interpenv
conda config --append channels conda-forge
conda install --file requirements.txt
```

**Comment by pblankley** [comment]
Sorry about being so heavy handed with the versions.  Since we had to use so many newer libraries (LIME, Shap, aif360), we were forced to be more specific to spend less time testing with various versions (and stick exclusively to Python 3.6). @SpyderRivera solution should work well.

Thanks for your patience with the install process!
